XarismaBundle\Entity\Fileops:
    type: entity
    table: fileops
    repositoryClass: XarismaBundle\Entity\FileopsRepository
    
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        action:
            type: string
            mullable: no
            length: 1
            fixed: false
            comment: 'Is this operation an Import or Export'
        eventTime:
            type: datetime
            nullable: true
            comment: ''
            column: eventTime
            comment: 'Time file was processed'       
        filename:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'Name of file'
        md5:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'MD5 of file contents'
        status:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: 'Status result of operation'
        recs:
            type: integer
            nullable: true
            length: 5
            default: 0
            comment: 'Number of records processed'
        errors:
            type: integer
            nullable: true
            length: 5
            default: 0
            comment: 'Number of errors during operation'
        customerNew:
            type: integer
            nullable: true
            length: 5
            default: 0
            comment: 'Customer records created'
        customerUpdate:
            type: integer
            nullable: true
            length: 5
            default: 0
            comment: 'Customer records updated'
        orderNew:
            type: integer
            nullable: true
            length: 5
            default: 0
            comment: 'Number of order records created'
        orderUpdate:
            type: integer
            nullable: true
            length: 5
            default: 0
            comment: 'Number of order records updated'
     
        datecreated:
            type: datetime
            nullable: true
            comment: ''
            default: CURRENT_TIMESTAMP
            column: dateCreated
        dateupdated:
            type: datetime
            nullable: true
            comment: ''
            column: dateUpdated
        deleted:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Soft Delete. True= deleted'
            default: '0'
            column: Deleted