XarismaBundle\Entity\Worklog:
    type: entity
    table: worklog
    repositoryClass: XarismaBundle\Entity\WorklogRepository
    
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        stationId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: station_id
        orderId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: order_id
        userId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: user_id
        stationstatus:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
            column: stationStatus
        comments:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        datecreated:
            type: datetime
            nullable: true
            comment: ''
            column: dateCreated
        dateupdated:
            type: datetime
            nullable: true
            comment: ''
            column: dateUpdated
        deleted:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: Deleted
    lifecycleCallbacks: {  }
